[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"   # keep 18; or set "20" if you want to silence the warning

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
